# Generated by Django 3.2.8 on 2021-11-14 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Prices')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creat time')),
            ],
            options={
                'verbose_name': 'Buyer bid',
                'verbose_name_plural': 'Buyer bid',
                'get_latest_by': 'updated',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Product category')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Product name')),
                ('img', models.ImageField(blank=True, default='', max_length=500, upload_to='img/', verbose_name='Product image')),
                ('detail', models.CharField(default='', max_length=1000, verbose_name='Product details')),
                ('sell_begin', models.DateTimeField(verbose_name='Auction Start Date')),
                ('sell_end', models.DateTimeField(verbose_name='Auction End Date')),
                ('price', models.FloatField(default=0.0, verbose_name='Prices')),
                ('status', models.CharField(choices=[('0', 'Auctioning'), ('1', 'Auction over')], default='0', max_length=2, verbose_name='Status')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creat time')),
                ('buy_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.category', verbose_name='Category')),
                ('sell_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Prices')),
                ('status', models.CharField(choices=[('0', 'Auction closed, unpaid'), ('1', 'Complete')], default='0', max_length=2, verbose_name='Status')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creat time')),
                ('buy_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.buyprice', verbose_name='Purchase history')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Information',
                'get_latest_by': 'updated',
            },
        ),
        migrations.AddField(
            model_name='buyprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='buyprice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
    ]
