# Generated by Django 3.2.8 on 2022-02-25 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0.0, verbose_name='Number')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('ttype', models.IntegerField(choices=[(1, 'Buy transfer'), (2, 'Not sold, company expense')], default=1, verbose_name='Transfer Type')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_from_user', to=settings.AUTH_USER_MODEL, verbose_name='From the user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Transfer in user')),
            ],
            options={
                'verbose_name': 'Money transfer information',
                'verbose_name_plural': 'Money transfer information',
                'ordering': ['-id'],
            },
        ),
    ]
