# Generated by Django 3.2.8 on 2022-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_transfermoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', 'Check pending'), ('1', 'Pass the check'), ('2', 'Unapproved'), ('3', 'Unidentified'), ('4', 'Pass identified'), ('5', 'Auction over')], default='0', max_length=2, verbose_name='Status'),
        ),
    ]
