# Generated by Django 3.2.8 on 2022-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_begin_stamp',
            field=models.FloatField(default=0, verbose_name='Auction start date time stamp seconds'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_end_stamp',
            field=models.FloatField(default=0, verbose_name='Auction end date time stamp seconds'),
        ),
    ]
